### ISSUE TITLE
Can't Read data (payload) from non-NDEF tag

### ISSUE THREAD

**Issue by BenCohenBenCohen** [don/phonegap-nfc-reader#14]
Hi,
I'm trying to read from my non-NDEF NFC card.
the only ACTION that is triggered is ACTION_TAG_DISCOVERED and i only can read the tag_info.

the tag's techs are "NfcB" and "IsoDep"

can anyone please help me get the data?

**Comment by don** [comment]
Duplicate of https://github.com/chariotsolutions/phonegap-nfc/issues/186
